### - Listar todos os autores
GET    /api/autores           

### - Buscar autor por ID
GET    /api/autores/:id      

### - Criar novo autor
POST   /api/autores           
Content-Type: application/json

{}

### - Atualizar autor
PUT    /api/autores/:id       
Content-Type: application/json

{}

### - Deletar autor
DELETE /api/autores/:id       
